name: Cleanup Old Tags and Release Branches

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly on Sunday at midnight
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Get all tags
      id: get_tags
      run: |
        git fetch --tags
        tags=$(git tag --sort=-creatordate)
        echo "::set-output name=tags::$tags"

    - name: Delete old tags and branches
      run: |
        tags_array=(${{ steps.get_tags.outputs.tags }})
        keep_count=0
        if [ ${#tags_array[@]} -gt $keep_count ]; then
          for tag in "${tags_array[@]:$keep_count}"; do
            echo "Deleting tag: $tag"
            git push --delete origin $tag

            branch="release/${tag}"
            if git rev-parse --quiet --verify "${branch}"; then
              git branch -D "${branch}"
              echo "Deleted branch ${branch}"
            else
              echo "Branch ${branch} does not exist"
            fi
            
            # branch="Release ${tag}"
            # if git show-ref --verify --quiet refs/heads/"$branch"; then
            #   echo "Deleting branch: $branch"
            #   git push --delete origin "$branch"
            # fi
          done
        else
          echo "No tags to delete"
        fi
