name: Dev:Build, Push & Create deploy PR
 
on:
  workflow_dispatch:
    inputs:
      refToBuild:
        description: "Branch, tag or commit SHA1 to build"
        required: true
        type: string
 
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    environment: development

    outputs:
      IMAGE_TAG: ${{ steps.capture-image-tag.outputs.IMAGE_TAG }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.refToBuild }}

      # Get Git vals for image tag format
      - name: Get Git Branch
        run: echo "BRANCH=`git rev-parse --abbrev-ref HEAD | sed -r 's/HEAD/pr/g'`" >> $GITHUB_ENV

      - name: Get Git Commit SHA (short)
        run: echo "SHA_SHORT=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Check Branch and Commit
        run: echo running on branch ${{ env.BRANCH }} with commit ${{ env.SHA_SHORT }}
 
      - name: Capture Image Tag
        id: capture-image-tag
        run: |
          TAG=${{ env.BRANCH }}_${{ env.SHA_SHORT }}
          echo "The image tag is $TAG"
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          echo "::set-output name=IMAGE_TAG::$TAG"
